name: trigger greeting
on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: mortenp1337/actions-semantic-release/greeting-action@greeting-action-v1.0.0

      
