name: trigger greeting
on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    uses: mortenp1337/actions-semantic-release/.github/workflows/release-greeting-action.yml@greeting-action-v1.1.0


