name: trigger action
on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: mortenp1337/actions-semantic-release/farewell-action@greeting-action-v1.1.1
        with: 
          person: 'v1.0.2 specified'
      - uses: mortenp1337/actions-semantic-release/farewell-action@greeting-action-v1.1.1
        with: 
          person: 'v1.0 specified'     
      - uses: mortenp1337/actions-semantic-release/farewell-action@greeting-action-v1.1.1
        with: 
          person: 'v1 specified'
