name: trigger multiple action versions
on:
  workflow_dispatch:

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: mortenp1337/actions-semantic-release/greeting-action@greeting-action-v1.1.1
      - uses: mortenp1337/actions-semantic-release/greeting-action@greeting-action-v1.1.1
      - uses: mortenp1337/actions-semantic-release/farewell-action@greeting-action-v1.1.1
      - uses: mortenp1337/actions-semantic-release/farewell-action@greeting-action-v1.1.1
        with: 
          person: 'v1 specified'

      
